# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pps_pb2 as pps__pb2


class PpsStatisticStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TotalStatistic = channel.unary_unary(
                '/PpsStatistic/TotalStatistic',
                request_serializer=pps__pb2.TotalStatisticRequest.SerializeToString,
                response_deserializer=pps__pb2.StatisticResponse.FromString,
                )
        self.FacultiesList = channel.unary_unary(
                '/PpsStatistic/FacultiesList',
                request_serializer=pps__pb2.FacultiesListRequest.SerializeToString,
                response_deserializer=pps__pb2.FacultiesListResponse.FromString,
                )
        self.FacultyStatistic = channel.unary_unary(
                '/PpsStatistic/FacultyStatistic',
                request_serializer=pps__pb2.FacultyStatisticRequest.SerializeToString,
                response_deserializer=pps__pb2.StatisticResponse.FromString,
                )
        self.ChairsList = channel.unary_unary(
                '/PpsStatistic/ChairsList',
                request_serializer=pps__pb2.ChairsListRequest.SerializeToString,
                response_deserializer=pps__pb2.ChairsListResponse.FromString,
                )
        self.ChairStatistic = channel.unary_unary(
                '/PpsStatistic/ChairStatistic',
                request_serializer=pps__pb2.ChairStatisticRequest.SerializeToString,
                response_deserializer=pps__pb2.StatisticResponse.FromString,
                )


class PpsStatisticServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TotalStatistic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FacultiesList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FacultyStatistic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChairsList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChairStatistic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PpsStatisticServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TotalStatistic': grpc.unary_unary_rpc_method_handler(
                    servicer.TotalStatistic,
                    request_deserializer=pps__pb2.TotalStatisticRequest.FromString,
                    response_serializer=pps__pb2.StatisticResponse.SerializeToString,
            ),
            'FacultiesList': grpc.unary_unary_rpc_method_handler(
                    servicer.FacultiesList,
                    request_deserializer=pps__pb2.FacultiesListRequest.FromString,
                    response_serializer=pps__pb2.FacultiesListResponse.SerializeToString,
            ),
            'FacultyStatistic': grpc.unary_unary_rpc_method_handler(
                    servicer.FacultyStatistic,
                    request_deserializer=pps__pb2.FacultyStatisticRequest.FromString,
                    response_serializer=pps__pb2.StatisticResponse.SerializeToString,
            ),
            'ChairsList': grpc.unary_unary_rpc_method_handler(
                    servicer.ChairsList,
                    request_deserializer=pps__pb2.ChairsListRequest.FromString,
                    response_serializer=pps__pb2.ChairsListResponse.SerializeToString,
            ),
            'ChairStatistic': grpc.unary_unary_rpc_method_handler(
                    servicer.ChairStatistic,
                    request_deserializer=pps__pb2.ChairStatisticRequest.FromString,
                    response_serializer=pps__pb2.StatisticResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PpsStatistic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PpsStatistic(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TotalStatistic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PpsStatistic/TotalStatistic',
            pps__pb2.TotalStatisticRequest.SerializeToString,
            pps__pb2.StatisticResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FacultiesList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PpsStatistic/FacultiesList',
            pps__pb2.FacultiesListRequest.SerializeToString,
            pps__pb2.FacultiesListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FacultyStatistic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PpsStatistic/FacultyStatistic',
            pps__pb2.FacultyStatisticRequest.SerializeToString,
            pps__pb2.StatisticResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChairsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PpsStatistic/ChairsList',
            pps__pb2.ChairsListRequest.SerializeToString,
            pps__pb2.ChairsListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChairStatistic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PpsStatistic/ChairStatistic',
            pps__pb2.ChairStatisticRequest.SerializeToString,
            pps__pb2.StatisticResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
